Global:
  use_gpu: True
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./models/rec_svtr_large_lpr/
  save_epoch_step: 1
  # evaluation is run every 2000 iterations after the 0th iteration
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: ppocr/utils/dict/lp_dict.txt
  # character_type: en
  max_text_length: 40
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_svtr_large_lpr.txt
  # d2s_train_image_shape: [3, 64, 256]


Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 1.e-8
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed
  one_dim_param_no_weight_decay: True
  lr:
    name: Cosine
    learning_rate: 3.75e-05 # 7.5e-05
    warmup_epoch: 5

Architecture:
  model_type: rec
  algorithm: SVTR
  # Transform:
  #   name: STN_ON
  #   tps_inputsize: [32, 64]
  #   tps_outputsize: [32, 320]
  #   num_control_points: 20
  #   tps_margins: [0.05,0.05]
  #   stn_activation: none
  Transform: null
  Backbone:
    name: SVTRNet
    img_size: [32, 320]
    out_char_num: 40
    out_channels: 384
    patch_merging: 'Conv'
    embed_dim: [192, 256, 512]
    depth: [3, 9, 9]
    num_heads: [6, 8, 16]
    mixer: ['Local','Local','Local','Local','Local','Local','Local','Local','Local','Local','Global','Global','Global','Global','Global','Global','Global','Global','Global','Global','Global']
    local_mixer: [[7, 11], [7, 11], [7, 11]]
    prenorm: False
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: pp_vn_real_1row_lp
    label_file_list:
    - pp_vn_real_1row_lp/train/rec.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: True
    num_workers: 16

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: pp_vn_real_1row_lp
    label_file_list:
    - pp_vn_real_1row_lp/val/rec.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 64
    num_workers: 16
